AzureWebApp/Models/ErrorViewModel.cs
namespace AzureWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AzureWebApp/Models/Order.cs
using System.ComponentModel.DataAnnotations;

namespace AzureWebApp.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public string OrderNo { get; set; }
        public double Total { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobile { get; set; }
        public List<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();
    }
}

AzureWebApp/Models/OrderDetails.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AzureWebApp.Models
{
    public class OrderDetails
    {
        [Key]
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public int Total { get; set; }
        public int OrderId { get; set; }

        [ForeignKey("OrderId")]
        public Order Order { get; set; }

        [ForeignKey("ProductId")]
        public Product Product { get; set; }


    }
}

AzureWebApp/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace AzureWebApp.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }

    }
}

AzureWebApp/ViewModels/ShoopingCartAddModel.cs
using System.ComponentModel.DataAnnotations;

namespace AzureWebApp.ViewModels
{
    public class ProductViewModel
    {
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public string ProductName { get; set; }
        public int Price { get; set; }
        public int Total { get; set; }
    }
}

AzureWebApp/ViewModels/ShoopingCartViewModel.cs
using AzureWebApp.Models;
using System.ComponentModel.DataAnnotations;

namespace AzureWebApp.ViewModels
{
    public class ShoopingCartViewModel
    {
        public string? CustomerName { get; set; }
        public string? CustomerMobile { get; set; }
        public string? ShippingAddress { get; set; }
        public List<ShoopingCartDetailsViewModel> ShoopingCartDetails { get; set; } = new List<ShoopingCartDetailsViewModel>();
    }

    public class ShoopingCartDetailsViewModel
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public double Total { get; set; }
    }
}

AzureWebApp/Controllers/HomeController.cs
using AzureWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AzureWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AzureWebApp/Controllers/ShoopingCartController.cs
using Azure.Storage.Queues.Models;
using AzureWebApp.Data;
using AzureWebApp.Models;
using AzureWebApp.Services.Queue;
using AzureWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Diagnostics;
using System.IO.Pipelines;
using System.Text.Json;

namespace AzureWebApp.Controllers
{
    public class ShoopingCartController : Controller
    {
        private readonly ILogger<ShoopingCartController> _logger;
        private AppDbContext _context;
        private const string QUEUE_NAME = "queue-cart-orders";
        private readonly IQueueService _queueService;
        public ShoopingCartController(ILogger<ShoopingCartController> logger, AppDbContext context , IQueueService queueService)
        {
            _logger = logger;
            _context = context;
            _queueService = queueService ?? throw new ArgumentNullException(nameof(queueService));
        }

        public async Task<IActionResult> Index()
        {
            var list = await _context.Products.Select(x => new ProductViewModel
            {
                ProductId = x.Id,
                ProductName = x.Name,
                Quantity = 0,
                Price = x.Price
            }).ToListAsync();

            return View(list);
        }
        private Product GetProductValue(int id)
        {
            var allProducts = ProductData.GetAllProducts();
            var product = allProducts.FirstOrDefault(y => y.Id == id);
            return product;
        }
        public IActionResult Create()
        {
            ViewBag.ProductList = ProductData.GetProductNames();
            return View();
        }

        //[HttpGet]
        //public async Task<IActionResult> CartAdd()
        //{
        //    var shoopingcart = await _context.ShoppingCarts.Include(x => x.ShoopingCartAddDetails).FirstOrDefaultAsync();
        //    var productIds = shoopingcart.ShoopingCartAddDetails.Select(y => y.ProductId);
        //    var products  =  await _context.Products.Where(x=> productIds.Contains(x.Id)).ToListAsync();     
        //    var model = new ShoopingCartViewModel();

        //    model.CustomerName = shoopingcart.CustomerName;
        //    model.ShippingAddress = shoopingcart.ShippingAddress;
        //    model.ShoopingCartAddDetails = shoopingcart.ShoopingCartAddDetails.Select(x => new ShoopingCartDetailsViewModel
        //    {
        //        Price = x.Price,
        //        ProductId = x.ProductId,
        //        Quantity = x.Quantity,
        //        Total = x.Total,
        //        ProductName = products.Where(y => y.Id == x.ProductId).FirstOrDefault().Name
        //    }).ToList();

            
        //    return View(model);
        //}

        [HttpPost]
        public async Task<IActionResult> Index(List<ProductViewModel> models)
        {
            var shoopingCart = new ShoopingCartViewModel();
            shoopingCart.CustomerMobile = "000-0000-000";
            shoopingCart.ShippingAddress = "North-Patenga, Chittagong";
            shoopingCart.CustomerName = "Mr.Patenga";

            shoopingCart.ShoopingCartDetails = models.Where(x => x.Quantity > 0).Select(x => 
                        new ShoopingCartDetailsViewModel
                        { ProductId = x.ProductId,
                            Quantity = x.Quantity,
                            Price = x.Price, 
                            Total = x.Quantity * x.Price 
                        }).ToList();
            var queueMessage = System.Text.Json.JsonSerializer.Serialize(shoopingCart);

            _queueService.SendMessage(QUEUE_NAME, queueMessage);

            return RedirectToAction(nameof(Index));
        }
    }
}

AzureWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AzureWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AzureWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AzureWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AzureWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoopingCart" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoopingCart" asp-action="CartAdd">Cart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AzureWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AzureWebApp/Views/ShoopingCart/CartAdd.cshtml
@model AzureWebApp.ViewModels.ShoopingCartViewModel
@using (Html.BeginForm())
{
    <h4>Shopping Cart</h4>
    <hr />

    <table class="table">
        <tr class="btn-secondary">
            <th>
                @Html.DisplayName("Product Name")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShoopingCartAddDetails[0].Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShoopingCartAddDetails[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShoopingCartAddDetails[0].Total)
            </th>
        </tr>

        @for (var i = 0; i < Model.ShoopingCartAddDetails.Count; i++)
        {
            @Html.HiddenFor(modelItem => Model.ShoopingCartAddDetails[i].ProductId)
            <tr class="btn-light">
                <td>
                    @Html.DisplayFor(modelItem => Model.ShoopingCartAddDetails[i].ProductName)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model.ShoopingCartAddDetails[i].Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.ShoopingCartAddDetails[i].Price)
                </td>
                <th>
                    @Html.DisplayNameFor(model => Model.ShoopingCartAddDetails[i].Total)
                </th>
            </tr>
        }

    </table>
    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName,"Customer Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerMobile,"Customer Mobile", htmlAttributes: new { @class = "control-label col-md-2 mt-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerMobile, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippingAddress,"Shipping Address", htmlAttributes: new { @class = "control-label col-md-2 mt-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShippingAddress, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Proceed To CheckOut" class="btn btn-default" />
            </div>
        </div>
    </div>
}  

AzureWebApp/Views/ShoopingCart/Index.cshtml
@model List<AzureWebApp.ViewModels.ProductViewModel>
@using (Html.BeginForm())
{

    <table class="table">
        <tr class="btn-secondary">
            <th>
                @Html.DisplayName("Product Name")
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Price)
            </th>
        </tr>

        @for (var i = 0; i < Model.Count; i++)
        {
            @Html.HiddenFor(modelItem => Model[i].ProductId)
            @Html.HiddenFor(modelItem => Model[i].ProductName)
            @Html.HiddenFor(modelItem => Model[i].Price)
            <tr class="btn-light">
                <td>
                    @Html.DisplayFor(modelItem => Model[i].ProductName)
                </td>
                <td>
                    @Html.EditorFor(modelItem => Model[i].Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].Price)
                </td>
            </tr>
        }

    </table>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Proceed To CheckOut" class="btn btn-secondary" />
            </div>
        </div>

    </div>
}  